"use client";

import { useEffect, useRef, useState } from "react";

/**
 * SearchUI — Pagefind integration.
 *
 * Pagefind's static bundle (/pagefind/pagefind-ui.js) is generated by the
 * `pagefind` CLI AFTER `next build`. It does NOT exist during `next dev`.
 * We dynamically import at runtime and show a stub in dev.
 *
 * Keyboard shortcut: Cmd/Ctrl + K opens the search dialog.
 */
export default function SearchUI() {
  const [open, setOpen] = useState(false);
  const mountedRef = useRef(false);
  const elRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setOpen((o) => !o);
      } else if (e.key === "Escape") {
        setOpen(false);
      }
    };
    const onExternalOpen = (ev: Event) => {
      const target = (ev.target as HTMLElement | null)?.closest?.(
        "[data-search-trigger]"
      );
      if (target) {
        ev.preventDefault();
        setOpen(true);
      }
    };
    window.addEventListener("keydown", onKey);
    document.addEventListener("click", onExternalOpen);
    return () => {
      window.removeEventListener("keydown", onKey);
      document.removeEventListener("click", onExternalOpen);
    };
  }, []);

  useEffect(() => {
    if (!open || mountedRef.current || !elRef.current) return;

    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/pagefind/pagefind-ui.js", { method: "HEAD" });
        if (!res.ok) throw new Error("pagefind-ui.js not available");

        const mod = (await import(
          /* webpackIgnore: true */ "/pagefind/pagefind-ui.js" as any
        )) as { PagefindUI: new (opts: any) => void };

        if (cancelled || !elRef.current) return;
        new mod.PagefindUI({
          element: elRef.current,
          showSubResults: true,
          showImages: false,
          resetStyles: false,
          translations: { placeholder: "Search all system designs…" },
        });
        mountedRef.current = true;
      } catch {
        if (elRef.current) {
          elRef.current.innerHTML =
            '<div class="search-dev-stub">Search is built post-deploy. Run <code>npm run build</code> then refresh.</div>';
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [open]);

  return (
    <>
      <button
        type="button"
        className="topbar-search-btn"
        onClick={() => setOpen(true)}
        aria-label="Open search"
      >
        <svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5">
          <circle cx="7" cy="7" r="5" />
          <path d="M11 11l3 3" strokeLinecap="round" />
        </svg>
        Search
        <span className="kbd">⌘K</span>
      </button>

      {open && (
        <div
          className="search-overlay"
          onClick={(e) => {
            if (e.target === e.currentTarget) setOpen(false);
          }}
        >
          <button
            type="button"
            className="search-dialog-close"
            aria-label="Close search"
            onClick={() => setOpen(false)}
          >
            ×
          </button>
          <div className="search-dialog">
            <div ref={elRef} />
          </div>
        </div>
      )}
    </>
  );
}
